# .github/workflows/deployment.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # needed for gh-pages deploy

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set BASE_PATH to /<repo-name> for next export + GitHub Pages
      - name: Set BASE_PATH
        run: echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      # Node 20 LTS + npm cache
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      # Optional: keep Browserslist DB fresh to remove warnings
      - name: Update Browserslist DB
        run: npx browserslist@latest --update-db

      # Cache Next.js build artifacts for faster CI
      - name: Cache Next build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: next-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build & Export
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          echo "Using BASE_PATH=$BASE_PATH"
          echo "NODE_OPTIONS=$NODE_OPTIONS"
          npm run build
          npm run export
          touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true
